# Generated by Django 5.2 on 2025-04-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('organizacion', models.CharField(max_length=200)),
                ('fecha_obtencion', models.DateField()),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('url_verificacion', models.URLField(blank=True, max_length=500, null=True)),
                ('archivo_certificado', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Certificación',
                'verbose_name_plural': 'Certificaciones',
                'ordering': ['-fecha_obtencion'],
            },
        ),
    ]
