# Generated by Django 5.2 on 2025-04-14 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría de Tecnología',
                'verbose_name_plural': 'Categorías de Tecnologías',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='certificacion',
            old_name='archivo_certificado',
            new_name='imagen',
        ),
        migrations.AddField(
            model_name='certificacion',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certifications/', verbose_name='PDF del Certificado'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='fecha_expiracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Expiración'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='fecha_obtencion',
            field=models.DateField(verbose_name='Fecha de Obtención'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='organizacion',
            field=models.CharField(max_length=100, verbose_name='Organización'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='url_verificacion',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Verificación'),
        ),
        migrations.AddField(
            model_name='certificacion',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='certificaciones', to='portfolio_app.technology'),
        ),
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='portfolio_app.technologycategory'),
        ),
    ]
